### ISSUE TITLE
Manpage udp6.1 uses hyphen instead of minus in line 215

### ISSUE THREAD

**Issue by alvarezp** [fgont/ipv6toolkit#36]
As reported by Debian lintian:
```
I: ipv6toolkit: hyphen-used-as-minus-sign usr/share/man/man1/udp6.1.gz:215
```

It's true, "-s" should be "\-s" in line 215:
```
$ cat -n manuals/udp6.1 | egrep '^\s+215'
   215	# udp6 -s fc00:1::/64 \-d fc00:1::1 \-a 22 \-F 100 \-l \-z 1 \-v
```

**Comment by fgont** [comment]
Is this really present in the current source, or did you find it in the v2.0 tarball?

**Comment by alvarezp** [comment]
Here it is: https://github.com/fgont/ipv6toolkit/blob/master/manuals/udp6.1#L215

**Comment by fgont** [comment]
Hola, Octavio,

No vi pull-request de esta... y chequeando el file en cuestion aprece
que no sufria de este error (al menos en mi working copy).

Podras chequear en el fuente actual si es que el error persiste?

Saludos, y gracias!
Fer




On 06/27/2015 02:03 PM, Octavio Alvarez wrote:
> As reported by Debian lintian:
> 
> |I: ipv6toolkit: hyphen-used-as-minus-sign usr/share/man/man1/udp6.1.gz:215
> |
> 
> It's true, "-s" should be "-s" in line 215:
> 
> |$ cat -n manuals/udp6.1 | egrep '^\s+215'
>    215  # udp6 -s fc00:1::/64 \-d fc00:1::1 \-a 22 \-F 100 \-l \-z 1 \-v
> |
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fgont/ipv6toolkit/issues/36>.
> 


-- 
Fernando Gont
SI6 Networks
e-mail: fgont@si6networks.com
PGP Fingerprint: 6666 31C6 D484 63B2 8FB1 E3C4 AE25 0D55 1D4E 7492

**Comment by alvarezp** [comment]
I still see it in my clone, so I created the following PR: https://github.com/fgont/ipv6toolkit/pull/37

**Comment by alvarezp** [comment]
Because #37 has been merged I will close this issue.
