### ISSUE TITLE
missing v2.0 sources

### ISSUE THREAD

**Issue by blshkv** [fgont/ipv6toolkit#38]
You anonounced v2.0 release at http://www.si6networks.com/tools/ipv6toolkit/ipv6toolkit-v2.0.tar.gz however it is not available. Please re-release it.

**Comment by fgont** [comment]
Fixed. Sorry, they were off-line during a migration of the site.

**Comment by blshkv** [comment]
Thanks. Also, it would be logical use github as the original source including releases, and post the copy on the website
