### ISSUE TITLE
chars are not always signed

### ISSUE THREAD

**Issue by bortzmeyer** [fgont/ipv6toolkit#39]
On a Raspberry Pi with FreeBSD:

cc  -O -pipe  -mfloat-abi=softfp  -Wall -o ra6 tools/ra6.c libipv6.o  -lpcap -lm
tools/ra6.c:488:18: warning: comparison of constant -2 with expression of type
      'char' is always false [-Wtautological-constant-out-of-range-compare]
                                if(preference<-2 || preference >1){
                                   ~~~~~~~~~~^~~
1 warning generated.

Probably because the toolkit (wrongly) assumes that chars are signed (not true on the ARM processor).

**Comment by alvarezp** [comment]
Does it get fixed for you if you change, in tools/ra6.c line 93, the 'char' type to 'signed char'?

**Comment by bortzmeyer** [comment]
Indeed, with this patch, the warning disappears. (Although I don't understand why this variable is a char, instead of a short int. It does not store characters.)

**Comment by fgont** [comment]
I was assuming sign in the char, and as long as it could hold -127 to 127 was enough. This is now changed -- among other reasons, we were assuming twos-complement for the signed integers, and strictly speaking you cannot assume that, either. Please check -- current i this respect. Thanks!
