### ISSUE TITLE
No result for scan6 on FreeBSD

### ISSUE THREAD

**Issue by bortzmeyer** [fgont/ipv6toolkit#40]
On two identical Raspberry Pi, on the same switch, one with FreeBSD and one with ArchLinux, scan6 -L works fine on Linux but returns nothing with FreeBSD.

FreeBSD: 

% sudo scan6   -L -i ue0   

ArchLinux: 
% sudo scan6   -L -i eth0 | wc -l
10

**Comment by fgont** [comment]
Could you provide a pcap packet trace so that I can see if it is failing to send the probe packets or what?
