### ISSUE TITLE
Something wrong in rs6.c 

### ISSUE THREAD

**Issue by BabauHo** [fgont/ipv6toolkit#43]
I think there is something wrong from line 751 to line 760.
But I have no idea with it.
Maybe, It causes that rs6's loop function does not work. 
Thanks.

**Comment by alvarezp** [comment]
Can you please be more specific? Thanks.

**Comment by alvarezp** [comment]
Maybe the weirdness is on line 757? -- https://github.com/fgont/ipv6toolkit/blob/master/tools/rs6.c#L757

**Comment by T-X** [comment]
Maybe @BabauHo means this issue / segfault: #56. That crashed badly for me.

**Comment by fgont** [comment]
Should be fixed by https://github.com/fgont/ipv6toolkit/pull/58
