### ISSUE TITLE
Do not abuse DESTDIR dir

### ISSUE THREAD

**Issue by blshkv** [fgont/ipv6toolkit#44]
There is seems confusion DESTDIR with PREFIX in Makefile. Here is GNU recommendations:
https://www.gnu.org/prep/standards/html_node/DESTDIR.html
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

There is the following line in the Makefile:
```DATAPATH= $(DESTDIR)$(PREFIX)/share/ipv6toolkit```

This is against gnu recommendation. As you can see from the links above, an additional "PREFIX" path should not be used at all. DESTDIR is good enough on its own.

Please fix Makefile or create a proper configure script (which is even better).

**Comment by blshkv** [comment]
P.S. needless to say, that no hardcoded paths should be used. Instead, the same DESTDIR variable should be used. For example, the in following file:
 tools/scan6.c: /usr/local/share

**Comment by alvarezp** [comment]
Hello. For the sake of completeness: besides the GNU recommendation are you aware of any particular use case that we are currently breaking?

**Comment by alvarezp** [comment]
The question about breaking use cases is regarding the use of PREFIX. The scan6.c hardcoded path case is self-evident.

**Comment by alvarezp** [comment]
In the case of the hardcoded paths in use by scan6.c: as part of "make install" an /etc/ipv6toolkit.conf is dynamically generated which allows for a configured location. This location is used by the scan6 tool on runtime. Only from the lack of this configuration file scan6 defaults to /usr/local/ to search for the files.

If you have any comments on this, can you please raise a separate issue for further discussion of this aspect? I would gladly continue the discussion in a separate issue, as this this would let us keep the discussion unmixed for both issues.

Thanks in advance.

**Comment by blshkv** [comment]
The practical reason why I raise it is that I'm creating an ebuild for Pentoo Linux.
The perfect software for us is then there is an automake ./configure script which allows us to adjust all variables and paths so that software would be installed correctly from our point of view.

In case of ipv6toolkit, we have a statical Makefile which is ok any many cases too. BUT, we have to hack our ebuild and declare non-standard PREFIX variable instead of already existing DESTDIR.

The second issue is about the hardcoded location of following oui.txt  service-names-port-numbers.csv  top-port-numbers.csv files where even PREFIX is not used. Well, there are command line parameters to specify each path in the latest snapshot but doesn't really make sense. 

I need to be able to install the tool in my locations with my paths for *all* files.

**Comment by blshkv** [comment]
Here is an example how Gentoo guys fixed Makefile:
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/ipv6-toolkit/files/ipv6-toolkit-1.3.1-destdir.patch
(the path two these 3 files was never fixed properly).

**Comment by alvarezp** [comment]
### Regarding the GNU that recommends against using PREFIX

The [GNU Coding Standards - DESTDIR](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) page makes no explicit recommendation against using additional variables. DESTDIR is, in fact, an additional prefix as explicitly exemplified by the text: ```$(INSTALL_PROGRAM) foo $(DESTDIR)$(bindir)/foo```, where ```$(DESTDIR)``` is an additional prefix to ```$(bindir)```. We do something similar.

The [GNU Coding Standards - Directory Variables page](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html), actually defines a ```prefix``` variable and suggests it to be ```/usr/local``` by default unless modified by the user (or packager).

Can you further specify what text makes the recommendation that an additional "PREFIX" path should not be used at all?


### Regarding the build

Even though IPv6 Toolkit does not use autotools it lets packagers specify their own DESTDIR and PREFIX during the build process.

DESTDIR is only for staging the installation but does not imply an installation prefix inside DESTDIR. For example, configuration files are not affected by DESTDIR.

This is exactly how it's currently done for [Debian packaging](https://github.com/alvarezp/ipv6toolkit/blob/debian/debian/rules#L12), by setting ```PREFIX=/usr``` and letting the Debian build system define DESTDIR. I see you are doing the same for your ebuild. This is currently the right way.

If DESTDIR included the final ```/usr``` part, then configuration files would end up in ```/usr/etc``` in your final package, which would not correct. Please correct me if I'm missing anything.

You mention an example about how Gentoo fixed the paths for the 1.3.1 version of IPv6 Toolkit. I acknowledge that 1.3.1 did not support staged install (or prefixes, whatsoever) but this changed in version 1.5.x when it got packaged for Debian. But then you say:

> (the path for these 3 files was never fixed properly)

Can you specify what path for what 3 files are you referring to?



### Regarding the use of hardcoded paths

I already made a comment about how this is not true. Paths can be set in /etc/ipv6toolkit.conf and only if you are explicitly overriding the default install behavior you could fall into hardcoded paths. This file is created dynamically during ```make all``` and installed on ```make install``` and defaults its values to paths prefixed by ```PREFIX```. But then you mention:

> I need to be able to install the tool in my locations with my paths for all files.

If you could ennumerate those paths it would give an insight on the specifics.


Thanks.

**Comment by blshkv** [comment]
DISTDIR and 'prefix' have two different meanings. gnu prefix (https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) is usually a --prefix variable for configure script which *should* adjust prefix during configuration/compilation stage. The typical values are '/usr/local' and '/usr'.
DESTDIR is a system environment variable. It allows to install a software into 'stage' or sandbox directory. 'etc' folder should be declared using --sysconfdir

I guess it's ok to introduce a new PREFIX variable since there is no configure script.

Let's focus on hardcoded path. 
/usr/local/share/ipv6toolkit/oui.txt
/usr/local/share/ipv6toolkit/service-names-port-numbers.csv
/usr/local/share/ipv6toolkit/top-port-numbers.csv

**Comment by alvarezp** [comment]
scan6 does not use hardcoded paths, except in fallback circumstances. You should be able to remove lines 22 and 23 from your ebuild script and it should work appropriately.

**Comment by blshkv** [comment]
ah, ok. Found relevant lines in the Makefile
```OUI-Database=$(PREFIX)/share/ipv6toolkit/oui.txt```

Closing the issue.

Thanks a lot for the quick responses!
