### ISSUE TITLE
Forcing DNS resolution

### ISSUE THREAD

**Issue by kaisersozet** [fgont/ipv6toolkit#49]
Hi,
I use this commaand to find the ip addresses that are used in an ipv6 network:
scan6 -v -i eth0 -d 2001:xxx:xxxx:xx::/64 -e -p echo
but I would  like to have at the same time the dns resolution. Is it possible ?
Thanks

**Comment by fgont** [comment]
You mean the reverse resolution? (i.e., given the IPv6 address, obtain the domain name... as in eg.. traceroute)
