### ISSUE TITLE
ipv6toolkit 2.0-1 build failure in ArchLinux

### ISSUE THREAD

**Issue by AWHubGit** [fgont/ipv6toolkit#67]
==> ERROR: A failure occurred in build().
Aborting...
[ipv6toolkit_failure.log](https://github.com/fgont/ipv6toolkit/files/5079196/ipv6toolkit_failure.log)

**Comment by alvarezp** [comment]
Duplicate of https://github.com/fgont/ipv6toolkit/pull/54

This is due to `-fno-common` being a new default in GCC 10. It is already fixed in commit 2bde90f3845234490549640dc6ed5712d84969ba.

You may want to backport it to 2.0.

**Comment by fgont** [comment]
This one has been fixed. thanks!
