### ISSUE TITLE
missing v2.0 sources (again)

### ISSUE THREAD

**Issue by mitchblank** [fgont/ipv6toolkit#70]
It looks like the tarball URL disappeared before (#38)  It seems to have happened again.
```
$ curl -v https://www.si6networks.com/tools/ipv6toolkit/ipv6toolkit-v2.0.tar.gz | head
[...]
< HTTP/1.1 404 Not Found
< Date: Sun, 06 Dec 2020 23:25:53 GMT
< Server: Apache/2.4.41 (Ubuntu)
< X-UA-Compatible: IE=edge
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Link: <https://www.si6networks.com/wp-json/>; rel="https://api.w.org/"
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
```

I stumbled upon this while debugging some Homebrew problems (see https://github.com/Homebrew/homebrew-core/pull/66372 )  I worked around it by using a copy of the tarball I found via google, but hopefully there is an official URL somewhere?

**Comment by fgont** [comment]
Apologies for the delay. Truth be told, the toolkit was mostly unmaintained for the last two-three years. I'm resyncing and making up now.
