### ISSUE TITLE
[BUG] conflict in Constants employed by decode_ipv6_address()

### ISSUE THREAD

**Issue by dianwoshishi** [fgont/ipv6toolkit#74]
https://github.com/fgont/ipv6toolkit/blob/babee5e172f680ff18354d9d9918c3f7356d48d3/tools/libipv6.h#L602
https://github.com/fgont/ipv6toolkit/blob/babee5e172f680ff18354d9d9918c3f7356d48d3/tools/libipv6.h#L613

```python
#define IID_EMBEDDEDIPV4_32		8192
#define IID_UNSPECIFIED			8192
```

maybe, the `IID_UNSPECIFIED` should be `16384`， which is `1 << 14`

**Comment by fgont** [comment]
Fixed! (thanks!)
