### ISSUE TITLE
Missing git tags for recent release?

### ISSUE THREAD

**Issue by robert-scheck** [fgont/ipv6toolkit#77]
According to the Internet, there is ipv6toolkit v2.0, but the download URL (http://www.si6networks.com/tools/ipv6toolkit/ipv6toolkit-v2.0.tar.gz) doesn't exist anymore (#70 claims this, too) - and there are also no git tags for any recent release of ipv6toolkit. Aside of that the actual versioning is very confusing in general (#62 claims this, too), because:

- [CHANGES.TXT](https://github.com/fgont/ipv6toolkit/blob/master/CHANGES.TXT#L1) talks about "SI6 Networks IPv6 Toolkit v2.1"
- [tools/ipv6toolkit.h](https://github.com/fgont/ipv6toolkit/blob/master/tools/ipv6toolkit.h#L1) talks about "SI6 Networks' IPv6 Toolkit v3.0"
- [tools/script6](https://github.com/fgont/ipv6toolkit/blob/master/tools/script6#L7) talks about "SI6 Networks IPv6 Toolkit v4.0"
- [tools/blackhole6](https://github.com/fgont/ipv6toolkit/blob/master/tools/blackhole6#L9) talks about "SI6 Networks IPv6 Toolkit v3.0"

The current situation makes it hard to impossible to properly package ipv6toolkit for further Linux distributions.

**Comment by fgont** [comment]
This is super-bad (apologies!).

I'll do this:
1) Ensure consisetncy. -- Please see: my [comment ](https://github.com/fgont/ipv6toolkit/issues/62#issuecomment-1205900973) for issue [#62 ](https://github.com/fgont/ipv6toolkit/issues/62)
2) Put back v2.0 in place rightaway
3) Plan to release v3.1 asap to fi all outstanding issues.

Thoughts?

**Comment by robert-scheck** [comment]
I like the proposal from @alvarezp in #62. Given I'm not sure where v3.1 would originate from (because I never saw a v3.0 so far), I am not sure what to answer here. If you refer to the version in the scripts itself…well, there also has been 4.0 already.

**Comment by robert-scheck** [comment]
Ping?

**Comment by sbrun** [comment]
Hello,

It would be great to have a new tagged release. Then the maintainers of the tool in various distributions could update it.
Thanks

**Comment by fgont** [comment]
THe toolkit had been rather unmaintained for the last couple of years. -- I'm catching up. -- Yhis one is now solved. Thanks!
