### ISSUE TITLE
Issues with the addr6 tool

### ISSUE THREAD

**Issue by helinhl** [fgont/ipv6toolkit#81]
Thank you for the excellent ipv6toolkit toolset. Recently, when I was using the addr6 tool in it, I noticed that even if I provided some IPv6 addresses that belonged to Embed-port type IID, it never counted them and always showed a value of 0. So I checked the source code of addr6. I discovered that stats->iidembeddedport is used in lines 1803-1804 of addr6.c, however, it is never updated in this file. I believe stats->iidembeddedport should be modified with stats->iidembeddedportfwd. Is that correct?

**Comment by fgont** [comment]
Fixed! thanks!
